config/routes.rb
Redpencil::Application.routes.draw do
  
  root :to => 'static#index'
  
  resources :posts, :except => [:edit, :update]
  
  post "users/login"

  get "users/check"

  get "users/logout"
  
  delete "users/destroy"
  
  get ':action' => 'static#:action'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content
  
  validates :content, :presence => true
  
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :token_hash, :token_consumed, :token_created_at
  
  validates :email, :presence => true, :uniqueness => true, :email => true
  
  has_many :posts, :dependent => :destroy
  
  def generate_token
    token = SecureRandom.hex(32).to_s
    self.token_hash = Digest::SHA256.new.hexdigest(token)
    self.token_created_at = Time.now
    self.token_consumed = false

    return token if self.save
    raise Exceptions::TokenGenerationError
  end
  
  def self.find_by_token(token)
    u = User.find_by_token_hash(Digest::SHA256.new.hexdigest(token))
    return nil if u.nil?
    
    raise Exceptions::TokenAlreadyConsumed if u.token_consumed
    raise Exceptions::TokenExpired if Time.now - u.token_created_at > PasswordlessConfig.config[:token_validity_period]
    
    # consume the token
    u.token_consumed = true
    
    return u if u.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :logged_in?
  
  private
  
  def current_user
    @current_user ||= User.find_by_id(session[:passwordless_uid])
  end
    
  def logged_in?
    current_user != nil
  end
  
  def require_login
    redirect_to root_path, :alert => 'You must be logged in to access this page' unless logged_in? or demo?
  end
  
  def demo?
    ["new", "create"].include?(params[:action]) and params[:demo] == "1"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_login
  
  #GET /posts -> list of posts
  def index
    @posts = current_user.posts
  end

  #GET /post/:id -> display post
  def show
    @post = current_user.posts.find_by_id(params[:id])
    redirect_to root_path, :alert => 'An error has occured.' unless @post
  end

  #GET /post/new -> html form for creating
  def new
    @post = Post.new()
  end

  #POST /posts -> create post
  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    
    if demo?
      render "demo"
      return
    end
    
    if @post.save
      redirect_to @post, :notice => 'Post successfully created.'
    else
      render :action => 'new', :alert => 'Post could not be created.' 
    end
  end

  #DELETE /post/:id -> remove post
  def destroy
    @post = current_user.posts.find_by_id(params[:id])
    if @post
      @post.destroy
      redirect_to posts_url, :notice => 'Post successfully destroyed.'
    else
      redirect_to root_path, :alert => 'An error has occured.'
    end
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  #nothing to to do here
  #see http://stackoverflow.com/a/4966764
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:destroy]
  
  def login
    if params[:email]
      u = User.find_by_email(params[:email])
    
      if u.nil?
        u = User.new(:email => params[:email])
      end
    
      begin
      token = u.generate_token
    
      TokenMailer.send_token(u, token).deliver
    
      flash[:notice] = "A login link has been sent to #{params[:email]}. Check your mailbox! (Don't forget to look in your spam folder)"
      
      rescue Exceptions::TokenGenerationError
        flash[:alert] = "Something wrong happened. Try to login again."
        flash[:alert] = u.errors.full_messages.first if u.invalid?
      end
    else
      flash[:alert] = "Something wrong happened. Try to login again."
    end
    redirect_to root_path
  end
  
  def check
    flash[:alert] = "Something wrong happened. Try to login again and we will send you a new link."
    if params[:token]
      begin
        u = User.find_by_token(params[:token])
        
        if !u.nil?
          reset_session
          session[:passwordless_uid] = u.id
          flash[:notice] = "Welcome back, #{u.email}"
          flash[:alert] = nil
          redirect_to posts_url
          return
        end
      rescue Exceptions::TokenAlreadyConsumed
        flash[:alert] = "Your login link has already been used. Try to login again and we will send you a new link."
      rescue Exceptions::TokenExpired
        flash[:alert] = "Your login link has expired. Try to login again and we will send you a new link."
      end
    end
    redirect_to root_path
  end

  def logout
    remove_session
    redirect_to root_path, :notice => "You have been logout successfully!"
  end
  
  def destroy
    if current_user
      remove_session
      current_user.destroy
      redirect_to root_path, :alert => "Your user and all your posts have been deleted!"
    end
  end
  
  private
  
  def remove_session
    reset_session
    session[:passwordless_uid] = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="masthead">
    <ul class="nav nav-pills pull-right">
        <li>
            <% if logged_in? %>
                <div class="btn-group">
                  <a class="btn btn-primary" href="/posts"><i class="icon-user icon-white"></i> <%= current_user.email %></a>
                  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/posts"><i class="icon-th-list"></i> Posts</a></li>
                    <li><a href="/users/logout"><i class="icon-remove"></i> Logout</a></li>
                    <li class="divider"></li>
                    <li><%= link_to("<i class=\"icon-trash\"></i> <span class=\"label label-warning\">Delete</span>".html_safe, '/users/destroy', :method => :delete, :confirm => "Are you sure you want to delete your user and all your posts?") %></li>
                  </ul>
                </div>
            <% else %>
                <%= form_tag('/users/login', :class => "form-inline") do %>
                    <div class="input-append">
                        <%= text_field_tag :email, nil, :placeholder => 'Your email', :class => "input-small", :type => "email", :id => "appendedInputButton" %>
                        <%= submit_tag 'Go', :class => "btn btn-primary" %>
                    </div>
                <% end %>
            <% end %>
        </li>
        <li>
            <%= link_to('About', '/about') %>
        </li>
        <li>
            <%= link_to('Credits', '/credits') %>
        </li>
    </ul>
    <h1 class="muted"><%= link_to "Red Pencil", root_path, :class => 'brand' %></h1>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Redpencil" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
</head>
<body>
    <div class="container-narrow">
        <%= render 'layouts/navigation' %>
          
        <hr />
        
        <div class="row-fluid">
            <div class="span12">
                <%= render 'layouts/messages' %>
                <div class="container-padded">
                    <%= yield %>
                </div>
            </div>
        </div>
        
        <hr />
        
        <footer class="pull-right">
            <ul class="inline">
              <li><p>A <%= link_to '10io', 'http://blog.10io.net'%> crazy project</p></li>
              <li><p>Rocketed by <%= link_to 'Heroku', 'http://www.heroku.com'%></p></li>
            </ul>
            
        </footer>
    </div>
    <div id="overlay"></div>
</body>
</html>

app/views/posts/_display_post.html.erb
<div>
    <pre><%= @post.content %></pre>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
    <div id="errorExplanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:</h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
  
    <div class="field">
        <%= f.text_area :content, :size => "80x30" %>
    </div>
    <% if !logged_in? %>
        <%= hidden_field_tag('demo', '1')%>
    <% end %>
<% end %>

app/views/posts/demo.html.erb
<h2>Your Post</h2>
<p>
    Here is your post
</p>
<%= render 'display_post'%>
<p>This was a demo of Freewriting! We hope you enjoyed it!</p>
<p>Don't be shy! Create an account and you will be able to save and manage your posts.</p>

app/views/posts/edit.html.erb
<h1>Post#edit</h1>
<p>Find me in app/views/post/edit.html.erb</p>

app/views/posts/index.html.erb
<h2>Posts</h2>

<table class="table">
    <thead>
        <tr>
            <th>Post</th>
            <th>Excerpt</th>
            <th>Created</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>

        <% for p in @posts %>        
        <tr>
            <td><%= link_to "#{p.id}", p %></td>
            <td><%= link_to "#{sanitize(truncate(p.content), :length => 30)}", p %></td>
            <td><%=p.created_at.strftime('%d %b. %Y')%>, <%=p.created_at.strftime('%H:%M')%> </td>
            <td><%= link_to '<i class="icon-remove-sign icon-white"></i>'.html_safe, p, :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
        <% end %>

    </tbody>
</table>

<p>
    <%= link_to '<i class="icon-plus-sign icon-white"></i> New post'.html_safe, new_post_path, {:class => 'btn btn-success'} %>
</p>

app/views/posts/new.html.erb
<h2>New Post</h2>
<p>Start typing whatever your mind is thinking about, after a while or if you stop typing, your post will be published.</p>
<p>Enjoy!</p>

<br />

<p>
    <%= render 'form' %>
</p>

app/views/posts/show.html.erb
<h2>Post created on <%=@post.created_at.strftime('%d %b. %Y')%>, <%=@post.created_at.strftime('%H:%M')%></h2>
<%= render 'display_post'%>

<%= link_to '<i class="icon-plus-sign icon-white"></i> New post'.html_safe, new_post_path, {:class => 'btn btn-success'} %>
<%= link_to '<i class="icon-list icon-white"></i> All posts'.html_safe, posts_path, {:class => 'btn btn-success'} %>